import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { calSans } from "./_app";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#10695b] to-[#034f43] font-sans">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1
            className={`text-5xl font-extrabold tracking-tight text-white sm:text-[5rem] ${calSans.className}`}
          >
            Should
          </h1>
          <div className="flex flex-col text-white p-4 shadow-2xl">
            <div className="">¡Image!</div>
            <div className="flex flex-col">
              <div>
                <h4>Cash</h4>
              </div>
              <div>Cody Currie, Milk</div>
            </div>
            <div className="flex justify-center">
              <div>Linea de tiempo</div>
            </div>
            <div className="flex justify-between">
              <h5>1:00</h5>
              <h5>-2:10</h5>
            </div>
            <div className="flex justify-around">
              <button>{"<<"}</button>
              <button>{">"}</button>
              <button>{">>"}</button>
            </div>
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
